import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Link from 'next/link';
import Image from 'next/image';
import './globals.css'
import RoLogo from '../../public/Rossetta_logo.png';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Rossetta',
  description: 'Generated by subbie',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <head>
        <link rel="stylesheet" as="style" href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/variable/pretendardvariable.min.css" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>  
      </head>
      <body>
        <div className='nav_back'>
          <div className='nav_content'>
            <div className="nav_basic">
              <Link href="/"><Image className="logo" src={RoLogo} alt='logo'/></Link>
              <Link className='nav_btn' href='/sign-edu'>수어교육</Link>
              <Link className='nav_btn' href='/'>수어실습</Link>
              <Link className='nav_btn' href='/'>오답노트</Link>
              <Link className='nav_btn' href='/'>1:1 문의</Link>
            </div>
            <div className='nav_customer'>
                <div className='cus_name'>000님</div>
                <img className='cus_up' src="/custom_up.png"/>
            </div>
          </div>
          {/* <div>{props.params.id}님</div> */}
        </div>
        {children} {/*아래 다른 페이지 폴더에서 layout.js 찾기*/}
      </body>
    </html>
  )
}
